//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace museum_restavration.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class restovratc_museumEntities : DbContext
    {
        public restovratc_museumEntities()
            : base("name=restovratc_museumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Выставки> Выставки { get; set; }
        public virtual DbSet<Растврация> Растврация { get; set; }
        public virtual DbSet<Реставратор> Реставратор { get; set; }
        public virtual DbSet<Специализация> Специализация { get; set; }
        public virtual DbSet<Тип_экспоната> Тип_экспоната { get; set; }
        public virtual DbSet<Экспонат> Экспонат { get; set; }
        public virtual DbSet<Экспонат_выставка> Экспонат_выставка { get; set; }
    }
}
