//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace museum_restavration.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Растврация
    {
        public int Код_реставрации { get; set; }
        public int Реставратор { get; set; }
        public int Эксопнат { get; set; }
        public System.DateTime Время_начала { get; set; }
        public System.DateTime Время_окончания { get; set; }
        public string Проделанная_работа { get; set; }
    
        public virtual Реставратор Реставратор1 { get; set; }
        public virtual Экспонат Экспонат { get; set; }
    }
}
