//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace museum_restavration.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Реставратор
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Реставратор()
        {
            this.Растврация = new HashSet<Растврация>();
        }
    
        public int Код_реставратора { get; set; }
        public string ФИО { get; set; }
        public int Специализация { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Растврация> Растврация { get; set; }
        public virtual Специализация Специализация1 { get; set; }
    }
}
