//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace museum_restavration.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Экспонат
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Экспонат()
        {
            this.Растврация = new HashSet<Растврация>();
            this.Экспонат_выставка = new HashSet<Экспонат_выставка>();
        }
    
        public int Код_экспоната { get; set; }
        public string Название { get; set; }
        public string Год_создания { get; set; }
        public string Год_обнаружения { get; set; }
        public int Тип_экспоната { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Растврация> Растврация { get; set; }
        public virtual Тип_экспоната Тип_экспоната1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Экспонат_выставка> Экспонат_выставка { get; set; }
    }
}
